module.exports = {
  name: 'Express frictionless-qa-image block',
  features: [
    {
      tcid: '0',
      name: '@frictionless-qa-image Remove background',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-remove-background',
      data: {
        h1Text: 'Remove the background',
        p1Text: 'Easily remove the background from images in Adobe Express, the quick and easy create-anything app. Continue editing your image in Adobe Express to quickly change the background, add graphics, and more.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG, PNG or WebP and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-remove-background @express @smoke @regression @t1',
    },
    {
      tcid: '1',
      name: '@frictionless-qa-image Resize image',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-resize',
      data: {
        h1Text: 'Free image resizer.',
        p1Text: 'Easily resize your images in one click using Adobe Express, the quick and easy create-anything app. Use the online photo resizer to instantly change the dimensions of any image to share across your social channels.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG, PNG or WebP and less than 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-resize-image @express @smoke @regression @t2',
    },
    {
      tcid: '2',
      name: '@frictionless-qa-image Convert to JPG',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-convert-to-jpg',
      data: {
        h1Text: 'PNG to JPG converter.',
        p1Text: 'Use our fast, easy, and free online image converter to convert from PNG to JPG in seconds',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be PNG or WebP and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-convert-to-jpg @express @smoke @regression @t2',
    },
    {
      tcid: '3',
      name: '@frictionless-qa-image Convert to PNG',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-convert-to-png',
      data: {
        h1Text: 'Convert your JPG to PNG in a snap.',
        p1Text: 'Convert to PNG in seconds with the Adobe Express free online JPG to PNG converter.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG or WebP and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-convert-to-png @express @smoke @regression @t2',
    },
    {
      tcid: '4',
      name: '@frictionless-qa-image Convert to SVG',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-convert-to-svg',
      data: {
        h1Text: 'Convert a JPG to SVG for free online.',
        p1Text: 'The free JPG (JPEG) to SVG converter tool from Adobe Express lets you upload your JPEG image and convert it to a vector in seconds.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG or PNG and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-convert-to-svg @express @smoke @regression @t2',
    },
    {
      tcid: '5',
      name: '@frictionless-qa-image Crop image',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-crop',
      data: {
        h1Text: 'Free online image cropper.',
        p1Text: 'The online Crop image tool from Adobe Express transforms your images into the perfect size in seconds.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG, PNG or WebP and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-crop-image @express @smoke @regression @t2',
    },
    {
      tcid: '6',
      name: '@frictionless-qa-image Change background',
      path: '/drafts/nala/test-gen/frictionless-qa-image/fqa-image-change-background',
      data: {
        h1Text: 'Free AI background changer.',
        p1Text: 'Use the AI background changer to remove blurry or distracting backgrounds in an instant. Swap it out with tons of Adobe Express backgrounds, your own images, and more.',
        dropZoneText: 'Drag and drop an imageor browse to upload.',
        buttonText: 'Upload your photo',
        p2Text: 'File must be JPEG, JPG, PNG or WebP and up to 40MB',
      },
      tags: '@frictionless-qa-image @frictionless-qa-change-background @express @smoke @regression @t2',
    },
  ],
};
