import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { build } from 'esbuild';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Use cwd so the build works when run from spectrum dir (e.g. npm run from any workspace root).
const SPECTRUM_DIR = path.resolve(process.cwd());
const ROOT_DIR = path.resolve(SPECTRUM_DIR, '../../../../../');

function rel(pathSegments) {
  return path.relative(ROOT_DIR, path.join(SPECTRUM_DIR, ...pathSegments));
}

const BANNER = `/* eslint-disable */
/* Generated by da-express-milo Spectrum Web Components bundler */
`;

const LIT_PATH_PATTERN = /^lit(\/.*)?$/;

const TARGET = 'es2021';
const DEFINE = { 'process.env.NODE_ENV': '"development"' };

const commonBuildOptions = {
  absWorkingDir: ROOT_DIR,
  define: DEFINE,
  platform: 'browser',
  format: 'esm',
  sourcemap: false,
  target: TARGET,
  minify: true,
  legalComments: 'none',
};

function rewriteImports() {
  return {
    name: 'rewrite-imports',
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        // Get the current entry point to avoid circular imports
        let [entryPath] = build.initialOptions.entryPoints;
        const entry = path.basename(String(entryPath), '.js');
        
        // Rewrite lit imports to use bundled lit
        if (LIT_PATH_PATTERN.test(args.path)) {
          return {
            path: './lit.js',
            external: true,
          };
        }
        
        // Rewrite @spectrum-web-components imports to use local bundles
        if (/@spectrum-web-components/.test(args.path)) {
          const [, module] = args.path.split('/');
          // Handle sub-imports like @spectrum-web-components/base/src/...
          const moduleName = module.split('/')[0];
          
          // Map to our bundled files
          const moduleMap = {
            'base': 'base',
            'button': 'button',
            'menu': 'menu',
            'overlay': 'overlay',
            'picker': 'picker',
            'popover': 'popover',
            'reactive-controllers': 'reactive-controllers',
            'shared': 'shared',
            'theme': 'theme',
          };
          
          const mappedModule = moduleMap[moduleName];
          // Don't rewrite if importing from the same module (avoid circular imports)
          if (mappedModule && mappedModule !== entry) {
            return {
              path: `./${mappedModule}.js`,
              external: true,
            };
          }
        }
        
        return undefined;
      });
    },
  };
}

// Special rewrite function for base.js - it needs to import from lit.js
function rewriteImportsForBase() {
  return {
    name: 'rewrite-imports-base',
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        // Rewrite lit imports to use bundled lit
        if (LIT_PATH_PATTERN.test(args.path)) {
          return {
            path: './lit.js',
            external: true,
          };
        }
        // Don't rewrite @spectrum-web-components imports for base - bundle them
        return undefined;
      });
    },
  };
}

const mods = fs.readdirSync(path.join(SPECTRUM_DIR, 'src')).filter(f => f.endsWith('.js'));

// First, bundle lit separately (paths relative to ROOT_DIR so esbuild resolves on any machine)
build({
  ...commonBuildOptions,
  bundle: true,
  banner: { js: BANNER },
  entryPoints: [rel(['src', 'lit.js'])],
  outfile: rel(['dist', 'lit.js']),
});

// Bundle base.js first - it needs to import from lit.js
build({
  ...commonBuildOptions,
  bundle: true,
  banner: { js: BANNER },
  entryPoints: [rel(['src', 'base.js'])],
  plugins: [rewriteImportsForBase()],
  outfile: rel(['dist', 'base.js']),
});

// Bundle icons first (before components that use them)
const iconMods = mods.filter(m => m.startsWith('icons-'));
iconMods.forEach((mod) => {
  build({
    ...commonBuildOptions,
    bundle: true,
    banner: { js: BANNER },
    entryPoints: [rel(['src', mod])],
    outfile: rel(['dist', mod]),
  });
});

// Then bundle each component (except base.js, lit.js, and icons)
mods.forEach((mod) => {
  if (mod === 'lit.js' || mod === 'base.js' || mod.startsWith('icons-')) return;
  
  build({
    ...commonBuildOptions,
    bundle: true,
    banner: { js: BANNER },
    entryPoints: [rel(['src', mod])],
    plugins: [rewriteImports()],
    outfile: rel(['dist', mod]),
  });
});

console.log('✅ Spectrum Web Components bundled successfully!');
