import fs from 'fs';
import { build } from 'esbuild';

const BANNER = `/* eslint-disable */
/* Generated by da-express-milo Spectrum Web Components bundler */
`;

const LIT_PATH_PATTERN = /^lit(\/.*)?$/;

const TARGET = 'es2021';
const DEFINE = { 'process.env.NODE_ENV': '"development"' };

function rewriteImports() {
  return {
    name: 'rewrite-imports',
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        // Get the current entry point to avoid circular imports
        let [entry] = build.initialOptions.entryPoints;
        entry = entry.replace('./src/', '').replace('.js', '');
        
        // Rewrite lit imports to use bundled lit
        if (LIT_PATH_PATTERN.test(args.path)) {
          return {
            path: './lit.js',
            external: true,
          };
        }
        
        // Rewrite @spectrum-web-components imports to use local bundles
        if (/@spectrum-web-components/.test(args.path)) {
          const [, module] = args.path.split('/');
          // Handle sub-imports like @spectrum-web-components/base/src/...
          const moduleName = module.split('/')[0];
          
          // Map to our bundled files
          const moduleMap = {
            'base': 'base',
            'theme': 'theme',
            'picker': 'picker',
            'menu': 'menu',
            'overlay': 'overlay',
            'popover': 'popover',
            'shared': 'shared',
            'reactive-controllers': 'reactive-controllers',
          };
          
          const mappedModule = moduleMap[moduleName];
          // Don't rewrite if importing from the same module (avoid circular imports)
          if (mappedModule && mappedModule !== entry) {
            return {
              path: `./${mappedModule}.js`,
              external: true,
            };
          }
        }
        
        return undefined;
      });
    },
  };
}

// Special rewrite function for base.js - it needs to import from lit.js
function rewriteImportsForBase() {
  return {
    name: 'rewrite-imports-base',
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        // Rewrite lit imports to use bundled lit
        if (LIT_PATH_PATTERN.test(args.path)) {
          return {
            path: './lit.js',
            external: true,
          };
        }
        // Don't rewrite @spectrum-web-components imports for base - bundle them
        return undefined;
      });
    },
  };
}

const mods = fs.readdirSync('./src').filter(f => f.endsWith('.js'));

// First, bundle lit separately
build({
  define: DEFINE,
  bundle: true,
  banner: { js: BANNER },
  entryPoints: ['./src/lit.js'],
  platform: 'browser',
  format: 'esm',
  sourcemap: false,
  target: TARGET,
  minify: true,
  outfile: './dist/lit.js',
});

// Bundle base.js first - it needs to import from lit.js
build({
  define: DEFINE,
  bundle: true,
  banner: { js: BANNER },
  entryPoints: ['./src/base.js'],
  platform: 'browser',
  format: 'esm',
  sourcemap: false,
  legalComments: 'none',
  target: TARGET,
  minify: true,
  plugins: [rewriteImportsForBase()],
  outfile: './dist/base.js',
});

// Bundle icons first (before components that use them)
const iconMods = mods.filter(m => m.startsWith('icons-'));
iconMods.forEach((mod) => {
  build({
    define: DEFINE,
    bundle: true,
    banner: { js: BANNER },
    entryPoints: [`./src/${mod}`],
    platform: 'browser',
    format: 'esm',
    sourcemap: false,
    legalComments: 'none',
    target: TARGET,
    minify: true,
    outfile: `./dist/${mod}`,
  });
});

// Then bundle each component (except base.js, lit.js, and icons)
mods.forEach((mod) => {
  if (mod === 'lit.js' || mod === 'base.js' || mod.startsWith('icons-')) return;
  
  build({
    define: DEFINE,
    bundle: true,
    banner: { js: BANNER },
    entryPoints: [`./src/${mod}`],
    platform: 'browser',
    format: 'esm',
    sourcemap: false,
    legalComments: 'none',
    target: TARGET,
    minify: true,
    plugins: [rewriteImports()],
    outfile: `./dist/${mod}`,
  });
});

console.log('✅ Spectrum Web Components bundled successfully!');
