export const ASYNC_REQUEST_STATUS = {
  NONE: 0,
  REQUESTED: 1,
  COMPLETED_SUCCESSFULLY: 3,
  COMPLETED_WITH_NO_RENDITIONS: 99,
  COMPLETED_WITH_NO_DATA_ERROR: 100,
  COMPLETED_WITH_UNKNOWN_ERROR: 101,
  COMPLETED_WITH_OK: 200,
  COMPLETED_WITH_NO_CONTENT: 204,
  COMPLETED_WITH_GENERIC_ERROR: 400,
  COMPLETED_WITH_NETWORK_ERROR_403: 403,
  COMPLETED_WITH_NETWORK_ERROR_404: 404,
  COMPLETED_WITH_NETWORK_ERROR_500: 500,
  COMPLETED_WITH_NETWORK_ERROR_503: 503,
  COMPLETED_WITH_NETWORK_ERROR_504: 504,
};

export const STOCK = 'STOCK';

export const CURATED_GALLERIES_STOCK = ['Wilderness', 'Flavour', 'Travel'];

export const CURATED_GALLERIES_IDS = {
  WILDERNESS: 'app.curatedgalleries.stock.gallery1',
  FLAVOUR: 'app.curatedgalleries.stock.gallery2',
  TRAVEL: 'app.curatedgalleries.stock.gallery3',
};

export const STOCK_DEFAULT_BATCH_SIZE = 36;
